# -*- coding:utf-8 -*-

from hichao.base.config import MYSQL_USER, MYSQL_PASSWD, MYSQL_HOST, MYSQL_PORT
from hichao.base.config import MYSQL_SLAVE_USER, MYSQL_SLAVE_PASSWD, MYSQL_SLAVE_HOST, MYSQL_SLAVE_PORT
from hichao.base.config import BETA_ECSHOP_MYSQL_USER, BETA_ECSHOP_MYSQL_PASSWD, BETA_ECSHOP_MYSQL_HOST, BETA_ECSHOP_MYSQL_PORT
SQLALCHEMY_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (MYSQL_USER, MYSQL_PASSWD, MYSQL_HOST, MYSQL_PORT, 'tuangou')
SQLALCHEMY_SLAVE_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (MYSQL_SLAVE_USER, MYSQL_SLAVE_PASSWD, MYSQL_SLAVE_HOST, MYSQL_SLAVE_PORT, 'tuangou')

SQLALCHEMY_BETA_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (BETA_ECSHOP_MYSQL_USER, BETA_ECSHOP_MYSQL_PASSWD, BETA_ECSHOP_MYSQL_HOST, BETA_ECSHOP_MYSQL_PORT, 'tuangou')

NO_TUANGOU = 0

TUANGOU_NORMAL = 1

TUANGOU_ABNORMAL = 2

