# -*- coding:utf-8 -*-

from hichao.base.config import MYSQL_USER, MYSQL_PASSWD, MYSQL_HOST, MYSQL_PORT
from hichao.base.config import MYSQL_SLAVE_USER, MYSQL_SLAVE_PASSWD, MYSQL_SLAVE_HOST, MYSQL_SLAVE_PORT
from hichao.base.config import READONLY_MYSQL_USER, READONLY_MYSQL_PASSWD, READONLY_MYSQL_HOST, READONLY_MYSQL_PORT
from hichao.base.config import MONGO_HOST, MONGO_PORT

MONGO_DBNAME = 'backend'
MONGO_SKU_IMG_TABLE = 'item_img'
MONGO_CONF_URL = '%s:%s' % (MONGO_HOST, MONGO_PORT)

BRAND_MYSQL_USER = READONLY_MYSQL_USER
BRAND_MYSQL_PASSWD = READONLY_MYSQL_PASSWD
BRAND_MYSQL_HOST = READONLY_MYSQL_HOST
BRAND_MYSQL_PORT = READONLY_MYSQL_PORT

READONLY_SQLALCHEMY_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (READONLY_MYSQL_USER, READONLY_MYSQL_PASSWD,
        READONLY_MYSQL_HOST, READONLY_MYSQL_PORT, 'wodfan')

SQLALCHEMY_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (MYSQL_USER, MYSQL_PASSWD, MYSQL_HOST, MYSQL_PORT, 'sku')
SQLALCHEMY_SLAVE_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (MYSQL_SLAVE_USER, MYSQL_SLAVE_PASSWD, MYSQL_SLAVE_HOST, MYSQL_SLAVE_PORT, 'sku')

BRAND_SQLALCHEMY_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (BRAND_MYSQL_USER, BRAND_MYSQL_PASSWD,
        BRAND_MYSQL_HOST, BRAND_MYSQL_PORT, 'wodfan')

SKU_PV_PREFIX = 'sku_pv_{0}'
SKU_UV_PREFIX = 'sku_uv_{0}'

