# -*- coding:utf-8 -*-

from hichao.base.config  import MYSQL_USER,MYSQL_PASSWD,MYSQL_HOST,MYSQL_PORT
from hichao.base.config  import ECSHOP_MYSQL_USER,ECSHOP_MYSQL_PASSWD,ECSHOP_MYSQL_HOST,ECSHOP_MYSQL_PORT
from hichao.base.config  import TEST_ECSHOP_MYSQL_USER,TEST_ECSHOP_MYSQL_PASSWD,TEST_ECSHOP_MYSQL_HOST,TEST_ECSHOP_MYSQL_PORT
from hichao.base.config  import BETA_ECSHOP_MYSQL_USER,BETA_ECSHOP_MYSQL_PASSWD,BETA_ECSHOP_MYSQL_HOST,BETA_ECSHOP_MYSQL_PORT

PANICBUYING_SQLALCHEMY_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (MYSQL_USER,MYSQL_PASSWD,MYSQL_HOST,MYSQL_PORT,'showlist')
ECSHOP_PANICBUYING_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (ECSHOP_MYSQL_USER,ECSHOP_MYSQL_PASSWD,ECSHOP_MYSQL_HOST,ECSHOP_MYSQL_PORT,'shop') 
TEST_ECSHOP_PANICBUYING_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (TEST_ECSHOP_MYSQL_USER,TEST_ECSHOP_MYSQL_PASSWD,TEST_ECSHOP_MYSQL_HOST,TEST_ECSHOP_MYSQL_PORT,'dev_b2c')
BETA_ECSHOP_PANICBUYING_CONF_URL = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (BETA_ECSHOP_MYSQL_USER,BETA_ECSHOP_MYSQL_PASSWD,BETA_ECSHOP_MYSQL_HOST,BETA_ECSHOP_MYSQL_PORT,'shop')
