# -*- coding:utf-8 -*-

STAR_DETAIL = 'starDetail'
SKU_DETAIL = 'itemDetail'
TOPIC_DETAIL = 'topicDetail'
THREAD_DETAIL = 'subjectDetail'
SEARCH_WORD = 'searchWord'
SEARCH_STAR = 'searchStar'
WEBVIEW = 'webview'
TOAST = 'toast'
DIALOG = 'dialog'
VIDEO = 'video'
SHARE = 'share'
SHOW_BIG_PIC = 'showBigPic'
OPEN_APP = 'openApp'
SPACE = 'space'
DETAIL = 'detail'
DETAIL_STAR = 'star'
DETAIL_SKU = 'sku'
DETAIL_THREAD = 'thread'
DETAIL_THEME = 'theme'
