# -*- coding:utf-8 -*-

CALENDAR_CELL = 'calendar'
CELL = 'cell'
COMMENT_CELL = 'comment'
FALL_STAR_CELL = 'waterfallStarCell'
HANG_TAG_CELL = 'hangtag'
ITEM_CELL = 'item'
LINK_CELL = 'linkDecoratedCell'
MORE_APP_CELL = 'appDetail'
MSG_CELL = 'thumbnailDecoratedMessageCell'
MSG_TEXT_CELL = 'msgText'
PRICE_CELL = 'priceDecoratedCell'
SEARCH_CELL = 'search'
SEARCH_STAR_CELL = 'searchStar'
SKU_CELL = 'sourceDecoratedCell'
THREAD_CELL = 'waterfallSubjectCell'
TOPIC_CELL = 'topic'
TOPIC_SKU_CELL = 'sourceDecoratedCell'
VIDEO_CELL = 'videoCell'
WORD_CELL = 'word'
WEBVIEW_CELL = 'webview'
SEARCH_TOPIC_CELL = 'searchTopicCell'
